package de.onyxmoon.modsync.command;

import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.command.system.CommandContext;
import com.hypixel.hytale.server.core.command.system.basecommands.AbstractPlayerCommand;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.World;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import de.onyxmoon.modsync.ModSync;
import de.onyxmoon.modsync.util.PermissionHelper;

import javax.annotation.Nonnull;
import java.awt.*;

/**
 * Root command: /modsync
 * Subcommands are automatically registered and help is generated by the command system.
 */
public class ModSyncCommand extends AbstractPlayerCommand {
    private final ModSync modSync;

    public ModSyncCommand(ModSync modSync) {
        super("modsync", "Synchronize mod lists from various sources");
        this.modSync = modSync;
    }

    @Override
    protected void execute(@Nonnull CommandContext commandContext,
                          @Nonnull Store<EntityStore> store,
                          @Nonnull Ref<EntityStore> ref,
                          @Nonnull PlayerRef playerRef,
                          @Nonnull World world) {
        if (!PermissionHelper.checkAdminPermission(playerRef)) {
            return;
        }

        // Command system should automatically show help for subcommands
        // If not, we could fall back to a simple message:
        playerRef.sendMessage(Message.raw("Use ").color(Color.GRAY)
                .insert(Message.raw("/modsync <subcommand>").color(Color.YELLOW))
                .insert(Message.raw(". Type ").color(Color.GRAY))
                .insert(Message.raw("/help modsync").color(Color.YELLOW))
                .insert(Message.raw(" for more info.").color(Color.GRAY)));
    }
}
