package de.onyxmoon.modsync.command;

import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.command.system.CommandContext;
import com.hypixel.hytale.server.core.command.system.CommandSender;
import com.hypixel.hytale.server.core.command.system.basecommands.CommandBase;
import de.onyxmoon.modsync.ModSync;
import de.onyxmoon.modsync.util.PermissionHelper;

import javax.annotation.Nonnull;
import java.awt.*;

/**
 * Root command: /modsync
 * Subcommands are automatically registered and help is generated by the command system.
 */
public class ModSyncCommand extends CommandBase {
    private final ModSync modSync;

    public ModSyncCommand(ModSync modSync) {
        super("modsync", "Synchronize mod lists from various sources");
        this.modSync = modSync;
    }

    @Override
    protected void executeSync(@Nonnull CommandContext commandContext) {
        if (!PermissionHelper.checkAdminPermission(commandContext)) {
            return;
        }

        // Command system should automatically show help for subcommands
        // If not, we could fall back to a simple message:
        CommandSender sender = commandContext.sender();
        sender.sendMessage(Message.raw("Use ").color(Color.GRAY)
                .insert(Message.raw("/modsync <subcommand>").color(Color.YELLOW))
                .insert(Message.raw(". Type ").color(Color.GRAY))
                .insert(Message.raw("/help modsync").color(Color.YELLOW))
                .insert(Message.raw(" for more info.").color(Color.GRAY)));
    }
}
